In [1]:
#load dataset

import pandas as pd
df=pd.read_csv("clean_movie_metadata.csv")
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3750,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
3751,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
3752,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
3753,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
3754,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3755 entries, 0 to 3754
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      3755 non-null   object
 1   director_name              3755 non-null   object
 2   num_critic_for_reviews     3755 non-null   float64
 3   duration                   3755 non-null   float64
 4   director_facebook_likes    3755 non-null   float64
 5   actor_3_facebook_likes     3755 non-null   float64
 6   actor_2_name               3755 non-null   object
 7   actor_1_facebook_likes     3755 non-null   float64
 8   gross                      3755 non-null   float64
 9   genres                     3755 non-null   object
 10  actor_1_name               3755 non-null   object
 11  movie_title                3755 non-null   object
 12  num_voted_users            3755 non-null   int64
 13  cast_total_facebook_likes  3755 non-null   int64
 14  actor_3_name               3755 non-null   object
 15  facenumber_in_poster       3755 non-null   float64
 16  plot_keywords              3755 non-null   object
 17  movie_imdb_link            3755 non-null   object
 18  num_user_for_reviews       3755 non-null   float64
 19  language                   3755 non-null   object
 20  country                    3755 non-null   object
 21  content_rating             3755 non-null   object
 22  budget                     3755 non-null   float64
 23  title_year                 3755 non-null   float64
 24  actor_2_facebook_likes     3755 non-null   float64
 25  imdb_score                 3755 non-null   float64
 26  aspect_ratio               3755 non-null   float64
 27  movie_facebook_likes       3755 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 821.5+ KB

In [3]:
df.isnull().sum()

color                        0
director_name                0
num_critic_for_reviews       0
duration                     0
director_facebook_likes      0
actor_3_facebook_likes       0
actor_2_name                 0
actor_1_facebook_likes       0
gross                        0
genres                       0
actor_1_name                 0
movie_title                  0
num_voted_users              0
cast_total_facebook_likes    0
actor_3_name                 0
facenumber_in_poster         0
plot_keywords                0
movie_imdb_link              0
num_user_for_reviews         0
language                     0
country                      0
content_rating               0
budget                       0
title_year                   0
actor_2_facebook_likes       0
imdb_score                   0
aspect_ratio                 0
movie_facebook_likes         0
dtype: int64

find the movies with the highest profit

In [6]:
df[df["gross"] == df["gross"].max()][["movie_title","gross"]]

  movie_title        gross
0     Avatar   760505847.0

find IMDB rank with top 100

In [9]:
df.sort_values(by="imdb_score", ascending=False).head(100)[["movie_title","imdb_score"]]

                      movie_title  imdb_score
1799    The Shawshank Redemption          9.3
3007               The Godfather          9.2
2547      The Godfather: Part II          9.0
64               The Dark Knight          9.0
2932                Pulp Fiction          8.9
...                           ...         ...
1832                     Warrior          8.2
2070               Into the Wild          8.2
325                 Finding Nemo          8.2
1633                    Die Hard          8.2
26    Captain America: Civil War          8.2

[100 rows x 2 columns]

best director

In [10]:
df.groupby("director_name")["imdb_score"].mean().sort_values(ascending=False).head(1)

director_name
Akira Kurosawa    8.7
Name: imdb_score, dtype: float64

popular genres

In [16]:
df["genres"].value_counts().head()

genres
Comedy|Drama|Romance    147
Drama                   141
Comedy|Drama            138
Comedy                  138
Comedy|Romance          131
Name: count, dtype: int64

critic favorite

In [12]:
df.groupby("actor_1_name")["imdb_score"].mean().sort_values(ascending=False).head(1)

actor_1_name
Takashi Shimura    8.7
Name: imdb_score, dtype: float64

audience favorite

In [13]:
df.groupby("actor_1_name")["num_voted_users"].sum().sort_values(ascending=False).head(1)

actor_1_name
Leonardo DiCaprio    9281136
Name: num_voted_users, dtype: int64