### *CASE STUDY*

In [45]:
#load dataset
import pandas as pd
df=pd.read_csv('messy_customer_dataset.csv')
df

,CustomerID,Name,Age,Gender,City,AnnualIncome,SpendingScore,TenureYears
0,1.0,Riya,NaN,Male,NaN,60899.0,81.0,3.0
1,2.0,Amit,20.0,Female,NaN,87909.0,NaN,9.0
2,3.0,Meera,24.0,Male,Bangalore,93738.0,NaN,NaN
3,4.0,Amit,27.0,Male,NaN,128359.0,NaN,NaN
4,5.0,Riya,43.0,Female,Hyderabad,75837.0,75.0,15.0
...,...,...,...,...,...,...,...,...
60,6.0,Amit,NaN,Female,NaN,NaN,61.0,14.0
61,NaN,Neha,34.0,Male,Chennai,NaN,91.0,NaN
62,21.0,Vikram,45.0,Female,NaN,NaN,NaN,NaN
63,6.0,Amit,NaN,Female,NaN,NaN,61.0,14.0
64,NaN,Neha,34.0,Male,Chennai,NaN,91.0,NaN

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustomerID     55 non-null     float64
 1   Name           62 non-null     object
 2   Age            50 non-null     float64
 3   Gender         49 non-null     object
 4   City           46 non-null     object
 5   AnnualIncome   45 non-null     float64
 6   SpendingScore  40 non-null     float64
 7   TenureYears    38 non-null     float64
dtypes: float64(5), object(3)
memory usage: 4.2+ KB

In [47]:
# check total missing values in each column
df.isnull().sum()

CustomerID       10
Name              3
Age              15
Gender           16
City             19
AnnualIncome     20
SpendingScore    25
TenureYears      27
dtype: int64

In [48]:
(df.isnull().sum() / len(df)) * 100

CustomerID       15.384615
Name              4.615385
Age              23.076923
Gender           24.615385
City             29.230769
AnnualIncome     30.769231
SpendingScore    38.461538
TenureYears      41.538462
dtype: float64

In [49]:
df.dropna(inplace=True)

In [51]:
df.reset_index(drop=True,inplace=True)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustomerID     6 non-null      float64
 1   Name           6 non-null      object
 2   Age            6 non-null      float64
 3   Gender         6 non-null      object
 4   City           6 non-null      object
 5   AnnualIncome   6 non-null      float64
 6   SpendingScore  6 non-null      float64
 7   TenureYears    6 non-null      float64
dtypes: float64(5), object(3)
memory usage: 516.0+ bytes

In [53]:
#DUPLICATE

df.duplicated().sum()

np.int64(0)

In [54]:
df[df.duplicated()]

Empty DataFrame
Columns: [CustomerID, Name, Age, Gender, City, AnnualIncome, SpendingScore, TenureYears]
Index: []

In [55]:
df = df.drop_duplicates()

In [56]:
#INCONSISTENCIES
#check data type

df.dtypes

CustomerID       float64
Name              object
Age              float64
Gender            object
City              object
AnnualIncome     float64
SpendingScore    float64
TenureYears      float64
dtype: object

In [58]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [61]:
pd.unique(df.Age)

array([43., 34., 19., 29., 38., 26.])

In [62]:
pd.unique(df.CustomerID)

array([ 5., 16., 18., 31., 52., 53.])

In [63]:
pd.unique(df.Name)

array(['Riya', 'Pooja', 'Arjun', 'Karan', 'Sneha'], dtype=object)

In [64]:
pd.unique(df.AnnualIncome)

array([ 75837.,  55792.,  28227., 111610., 116683.,  34042.])

In [65]:
pd.unique(df.SpendingScore)

array([75., 19., 34., 24., 15., 74.])

In [66]:
pd.unique(df.TenureYears)

array([15.,  8., 10.,  1., 14.])

In [67]:
df

,CustomerID,Name,Age,Gender,City,AnnualIncome,SpendingScore,TenureYears
0,5.0,Riya,43.0,Female,Hyderabad,75837.0,75.0,15.0
1,16.0,Pooja,34.0,Male,Delhi,55792.0,19.0,8.0
2,18.0,Arjun,19.0,Female,Hyderabad,28227.0,34.0,10.0
3,31.0,Karan,29.0,Male,Chennai,111610.0,24.0,1.0
4,52.0,Riya,38.0,Male,Delhi,116683.0,15.0,14.0
5,53.0,Sneha,26.0,Male,Hyderabad,34042.0,74.0,14.0

In [68]:
#OUTLIERS

Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df[(df['Age'] < lower) | (df['Age'] > upper)]

Empty DataFrame
Columns: [CustomerID, Name, Age, Gender, City, AnnualIncome, SpendingScore, TenureYears]
Index: []